name: Your New Jekyll Site
markdown: redcarpet
pygments: true
exclude:
  - jekyll-import-0.2.0
baseurl: /tikal_jekyll_website
nav_links: [ "/about", "/solutions", "/careers", "/events", "/contact" ]
assets:
  debug: true
  baseurl: /tikal_jekyll_website/assets
  compress:
    css:  sass
    js:   uglifier
    debug: true
paginate: 10
