name: Your New Jekyll Site
markdown: redcarpet
pygments: true
exclude:
  - jekyll-import-0.2.0
baseurl: /tikal_jekyll_website
nav_links: [ "/about", "/solutions", "/careers", "/events", "/contact" ]
assets:
  baseurl: /tikal_jekyll_website/assets
  compress:
    css:  sass
    js:   uglifier
paginate: 10

groups:
  - group:
      name: alm
      tag: alm
      title: ALM | Tikal
      header_title: ALM
      header_subtitle: Ahoy ALM Pirates! Welcome to Tikal's ALM Domain.
  - group:
      name: java
      tag: java
      title: Java | Tikal
      header_title: Java
      header_subtitle: Beware Java Jedi... You have just entered Tikal's Java Domain.
  - group:
      name: js
      tag: js
      title: JS | Tikal
      header_title: JS
      header_subtitle: Welcome JS Ninjas! You have just entered Tikal's JS Domain.
  - group:
      name: net
      tag: .net
      title: .NET | Tikal
      header_title: .NET
      header_subtitle: What up .NET Geeks ? Welcome to Tikal's .NET Domain.
  - group:
      name: ror
      tag: ror
      title: RoR | Tikal
      header_title: RoR
      header_subtitle: Hello there RoR Gurus. This is Tikal's RoR Domain.
