name: Your New Jekyll Site
markdown: redcarpet
pygments: true
nav_links: [ "about", "solutions", "careers", "events", "contact" ]
assets:
  compress:
    css:  sass
    js:   uglifier
groups:
  - ALM
  - JAVA
  - JS
  - .NET
  - RoR
paginate: 5
  
